### ISSUE TITLE
OS Commands: What does Rust do about OS command access?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#26]
https://cwe.mitre.org/data/definitions/214 Invocation of Process Using Visible Sensitive Information

A process is invoked with sensitive command-line arguments, environment variables, or other elements that can be seen by other processes on the operating system.

**Comment by blaqat** [comment]
Rust provides the [std::env::var](https://doc.rust-lang.org/std/env/fn.var.html) which you should use to get environment variables safely. 

But rust does not prevent you from using sensitive information in command arguments inherently when using [std::env::args](https://doc.rust-lang.org/std/env/struct.Args.html).

This is more up to the developer (and user?) I believe.

**Comment by andymeneely** [comment]
Yeah come to think of it this is domain-driven and a language can't help with this. No Help, or Langs Won't Help
