### ISSUE TITLE
Crypto: What, if any, forms of cryptography and authentication are in std?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#27]
https://cwe.mitre.org/data/definitions/CWE-295	Improper Certificate Validation
https://cwe.mitre.org/data/definitions/CWE-306	Missing Authentication for Critical Function

**Comment by blaqat** [comment]
Rust has no cryptography related tools in the std these are all provided through external libraries.
Both should be in rust provides no help.

**Comment by andymeneely** [comment]
Agreed - it's pretty clear that even the low-level stuff is in crates. I'm going with No Help or Langs Won't Help here.
