### ISSUE TITLE
Serialization/Deserialization: are there any forms of it in std? How much does, e.g. serde, implement on its own vs delegate to std?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#31]
https://cwe.mitre.org/data/definitions/502	Deserialization of Untrusted Data

**Comment by blaqat** [comment]
I believe there is no serilization/deserialization tools in std.

**Comment by MatthewFluet** [comment]
Agreed, nothing in std regarding serialization/deserialization.  `serde` is a recommended community crate.

**Comment by andymeneely** [comment]
Great! Closing this as "No Help, or Langs Won't Help"
