### ISSUE TITLE
Power consumption: is power consumption explicitly tracked or handled in std Rust? Or is that a library?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#36]
https://cwe.mitre.org/data/definitions/920	Improper Restriction of Power Consumption

**Comment by blaqat** [comment]
I cannot find anything relating to std handling power consumption.

Did however find two related libraries 
https://github.com/ThijsRay/coppers
https://github.com/hubblo-org/scaphandre

**Comment by andymeneely** [comment]
Seemed like a stretch to begin with - it's under hardware classification anyway, so highly unlikely in std.
